deploy:
  provider: pypi
  user: w1r0x
  password:
    secure: DV8HmIux4NNSZw+6KnDr2yJ6HWG+uAowwTTIvYwcas5nlzjZFmYiqbk2uPxNBgKY6tWJI3yRB6MxAc8BIB3UWE+jUhb2JQUqTd00UOwxiCS0zj2gm5CU2+SSaSgDeiwZmsqyWuklOlQSbxeu0ZaGfaV3z6Cqu9g51MeKAWTovN6B809YdrmcmSC5XQ1D1tSa8US2nrF41tmPklMiIlAlu5AF3p/9v12mflZiP5Bkh72zNU4x2jeHRvwczQ4Oh0+VrYqvcy1KFRTbpNz/ExZ2hH40yTTPYE8bekYXvfRfEKq5ghpOUP5viW23+XD4WyH6ccdVYAR6b6eY2+KaGl/oAZxp3W2QA6L7K4jARhpZe9GK7Vw7znzfgJJ4sgPl7PJDRKtOTvABeOG5ppNcZazYkgeZNsUwyH5s+2OwM3d5LtpyxxFxpvzXqWprTHMiFaVSfHNvON2Bllteb1yz0lPXf6BrcTgcK2N89C2QSHF0WrOGyirfYpRKgg/y5p8BJ0B3zwM2BC/hxVlbRThFuYgAwlkRb5dcm5KvmZT64PffHp2U1I5I4EzJAm43+TmeMDq+/0VOuBVspL3vaRDtaRVZasNqbOYoIMbzMQK0ACCZs802hZ4yPgkdD8qBiyr3eKLwAJJ+lRvI0HT1mYYQEINPo7hj0N8rUdkThOpBauNO6wQ=
  on:
    tags: true
